site_name: COMP6203 Intelligent Agents 中文学习指南

nav:
    - Home: index.md
    - Quick Start: start.md
    - Basic Concept (Lab1): basic.md
    - Simple Agent (Lab2): simple.md
    - Opponent Model (Lab3): opponent.md
    - User Model (Lab4): user.md
    - Choose and Accept: action.md
    - Submission and Report: report.md
    - Monologue: final.md

theme: readthedocs

markdown_extensions:
    - pymdownx.arithmatex:
          generic: true

extra_javascript:
    - javascripts/config.js
    - https://polyfill.io/v3/polyfill.min.js?features=es6
    - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
